# Mocco Supabase 本地开发配置
# 文档: https://supabase.com/docs/guides/cli/config

project_id = "mocco"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:8081"
additional_redirect_urls = ["http://localhost:8081"]
enable_signup = true
enable_anonymous_sign_ins = true

[storage]
enabled = true
file_size_limit = "10MiB"
